config/routes.rb
Rails.application.routes.draw do
  root 'properties#index'
  resources :properties
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
    
    
    validate :diff
    
    def diff
if minut <= minut1
    errors.add(:How_many_minutes_walk, "pls check again how it works")
# elsif minut = minut1
#     errors.add(:How_many_minutes_walk, "must be different")
    end
    end
end

app/models/propety.rb
class Propety < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:propert, :rent, :address, :building_age, :remarks, :namer, :station, :minut, :namer1, :station1, :minut1)
    end
end

app/controllers/propeties_controller.rb
class PropetiesController < ApplicationController
  before_action :set_propety, only: [:show, :edit, :update, :destroy]

  # GET /propeties
  # GET /propeties.json
  def index
    @propeties = Propety.all
  end

  # GET /propeties/1
  # GET /propeties/1.json
  def show
  end

  # GET /propeties/new
  def new
    @propety = Propety.new
  end

  # GET /propeties/1/edit
  def edit
  end

  # POST /propeties
  # POST /propeties.json
  def create
    @propety = Propety.new(propety_params)

    respond_to do |format|
      if @propety.save
        format.html { redirect_to @propety, notice: 'Propety was successfully created.' }
        format.json { render :show, status: :created, location: @propety }
      else
        format.html { render :new }
        format.json { render json: @propety.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /propeties/1
  # PATCH/PUT /propeties/1.json
  def update
    respond_to do |format|
      if @propety.update(propety_params)
        format.html { redirect_to @propety, notice: 'Propety was successfully updated.' }
        format.json { render :show, status: :ok, location: @propety }
      else
        format.html { render :edit }
        format.json { render json: @propety.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /propeties/1
  # DELETE /propeties/1.json
  def destroy
    @propety.destroy
    respond_to do |format|
      format.html { redirect_to propeties_url, notice: 'Propety was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_propety
      @propety = Propety.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def propety_params
      params.require(:propety).permit(:property, :rent, :adress, :building, :remark)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/propeties_helper.rb
module PropetiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExamE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Property %>
    <%= form.text_field :propert %>
  </div>

  <div class="field">
    <%= form.label :Rent %>
    <%= form.number_field :rent %>yen
  </div>

  <div class="field">
    <%= form.label :Address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :Building_age %>
    <%= form.number_field :building_age %>year/years old
  </div>

  <div class="field">
    <%= form.label :Remarks %>
    <%= form.text_area :remarks %>
  </div>
<hr>

<strong>Name_of_railway_line 1</strong>
  <div class="field">
    <%= form.label :Name_of_railway_line %>
    <%= form.text_field :namer %>
  </div>

  <div class="field">
    <%= form.label :Station_name %>
    <%= form.text_field :station %>
  </div>

  <div class="field">
    *<%= form.label :How_many_minutes_walk %>
    <%= form.number_field :minut %>min/mins
  </div>
  <strong>Name_of_railway_line 1</strong>
  <div class="field">
    <%= form.label :Name_of_railway_line %>
    <%= form.text_field :namer1 %>
  </div>

  <div class="field">
    <%= form.label :Station_name %>
    <%= form.text_field :station1 %>
  </div>

  <div class="field">
    *<%= form.label :How_many_minutes_walk %>
    <%= form.number_field :minut1 %>min/mins
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing information of Property</h1>
<%= render 'form', property: @property %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties List</h1>

<table style="width: 60%; ">
  <thead  >
    <tr>
      <th>Property</th>
      <th>Rent</th>
      <th>Address</th>
      <th>Building age</th>
      <th>Remarks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody >
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.propert %></td>
        <td><%= property.rent %></td>
        <td><%= property.address %></td>
        <td><%= property.building_age %></td>
        <td><%= property.remarks %></td>
        
        <td><%= link_to 'Detail', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'Register Property', new_property_path %>

app/views/properties/new.html.erb
<h1>Register property</h1>

<%= render 'form', property: @property %>

app/views/properties/show.html.erb
<h1> Property Details</h1>
<p id="notice"><%= notice %></p>

<p>
  Property: <%= @property.propert %>
</p>

<p>
 Rent: <%= @property.rent %>yern
</p>

<p>
  Address: <%= @property.address %>
</p>

<p>
Building age: <%= @property.building_age %>
</p>

<p>
  Remarks:<%= @property.remarks %>
</p>
<hr>
<b> Nearest station 1</b>
<p>
Name of railway line:<%= @property.namer %>
</p>

<p>
 Station name: <%= @property.station %>
</p>

<p>
  How many minutes walk: <%= @property.minut %>/mins
</p>
<b> Nearest station 2</b>
<p>
 Name of railway line:<%= @property.namer1 %>
</p>

<p>
 Station name: <%= @property.station1 %>
</p>

<p>
  How many minutes walk:<%= @property.minut1 %>mins
</p>

<%= link_to 'Edit_propety_information', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/propeties/_form.html.erb
<%= form_for(propety) do |f| %>
  <% if propety.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(propety.errors.count, "error") %> prohibited this propety from being saved:</h2>

      <ul>
      <% propety.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :property %>
    <%= f.text_area :property %>
  </div>

  <div class="field">
    <%= f.label :rent %>
    <%= f.text_field :rent %>
  </div>

  <div class="field">
    <%= f.label :adress %>
    <%= f.text_field :adress %>
  </div>

  <div class="field">
    <%= f.label :building %>
    <%= f.text_field :building %>
  </div>

  <div class="field">
    <%= f.label :remark %>
    <%= f.text_area :remark %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/propeties/edit.html.erb
<h1>Editing Propety</h1>

<%= render 'form', propety: @propety %>

<%= link_to 'Show', @propety %> |
<%= link_to 'Back', propeties_path %>

app/views/propeties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Propeties</h1>

<table>
  <thead>
    <tr>
      <th>Property</th>
      <th>Rent</th>
      <th>Adress</th>
      <th>Building</th>
      <th>Remark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @propeties.each do |propety| %>
      <tr>
        <td><%= propety.property %></td>
        <td><%= propety.rent %></td>
        <td><%= propety.adress %></td>
        <td><%= propety.building %></td>
        <td><%= propety.remark %></td>
        <td><%= link_to 'Show', propety %></td>
        <td><%= link_to 'Edit', edit_propety_path(propety) %></td>
        <td><%= link_to 'Destroy', propety, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Propety', new_propety_path %>

app/views/propeties/new.html.erb
<h1>New Propety</h1>

<%= render 'form', propety: @propety %>

<%= link_to 'Back', propeties_path %>

app/views/propeties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Property:</strong>
  <%= @propety.property %>
</p>

<p>
  <strong>Rent:</strong>
  <%= @propety.rent %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @propety.adress %>
</p>

<p>
  <strong>Building:</strong>
  <%= @propety.building %>
</p>

<p>
  <strong>Remark:</strong>
  <%= @propety.remark %>
</p>

<%= link_to 'Edit', edit_propety_path(@propety) %> |
<%= link_to 'Back', propeties_path %>